package com.example.quizapp

object Constants {
    public val USER_NAME: String = "user_name"
    public val TOTAL_QUESTIONS: String = "total_ques"
    public val CORRECT_ANS: String = "correct_ans"
    public val SELECTED_QUIZ: String = "selected_quiz"

    fun getQuestionsQuiz1(): ArrayList<Question>{
        var list = ArrayList<Question>()
        var ques1 = Question(1,"Which sport equipment are these?",R.drawable.cricket,"Cricket","Baseball","Volleyball","Hockey",1)
        list.add(ques1)
        var ques2 = Question(2,"Which sport equipment are these?",R.drawable.badminton,"Tennis","Volleyball","Badminton","Table Tennis",3)
        list.add(ques2)
        var ques3 = Question(3,"Which sport equipment are these?",R.drawable.tt,"Snooker","Soft Tennis","Table Tennis","Piddle Ball",3)
        list.add(ques3)
        var ques4 = Question(4,"Which sport equipment are these?",R.drawable.football,"Basket Ball","KickBall","Rugby","Football",4)
        list.add(ques4)
        var ques5 = Question(5,"Which sport equipment are these?",R.drawable.archery,"Archery","Shooting","Gymnastics","None",1)
        list.add(ques5)
        var ques6 = Question(6,"Which sport equipment are these?",R.drawable.basketball,"Football","Basket Ball","Volleyball","None",2)
        list.add(ques6)
        var ques7 = Question(7,"Which sport equipment are these?",R.drawable.volleyball,"Volleyball","BasketBall","Football","Squash",1)
        list.add(ques7)
        var ques8 = Question(8,"Which sport equipment are these?",R.drawable.boxing,"Wrestling","Boxing","Hurricing","WES",2)
        list.add(ques8)
        var ques9 = Question(9,"Which sport equipment are these?",R.drawable.cycling,"Racing","Running","Gymnastics","Cycling",4)
        list.add(ques9)
        var ques10 = Question(10,"Which sport equipment are these?",R.drawable.snooker,"Table Tennis","Snooker","Bowling","None",2)
        list.add(ques10)
        return list
    }

    fun getQuestionsQuiz2(): ArrayList<Question>{
        var list = ArrayList<Question>()
        var ques1 = Question(1,"Which Indian Famous personality is this?",R.drawable.apj,"Narayana Murthy","A.P.J Abdul Kalam","Laxmanrao Kashinath","Dhirubhai",2)
        list.add(ques1)
        var ques2 = Question(2,"Which Indian Famous personality is this?",R.drawable.bs,"Bhagat Singh","Udham Singh","Lala Lajpat Rai","None of Above",1)
        list.add(ques2)
        var ques3 = Question(3,"Which Indian Famous personality is this?",R.drawable.atv,"Atal Bihari Vajpayee","Narendra Modi","Manmohan Singh","H.D Deve Gowda",1)
        list.add(ques3)
        var ques4 = Question(4,"Which Indian Famous personality is this?",R.drawable.br,"Laxmanrao Kashinath","H.D Deve Gowda","B.R Ambedkar","Sayajirao Gaekwad",3)
        list.add(ques4)
        var ques5 = Question(5,"Which Indian Famous personality is this?",R.drawable.jln,"Rajiv Gandhi","Jawaharlal Nehru","Monarji Desao","Subhash Chandra Bose",2)
        list.add(ques5)
        var ques6 = Question(6,"Which Indian Famous personality is this?",R.drawable.mg,"Narayana Murthy","KaramChand Gandhi","Dhirubhai","Mahatma Gandhi",4)
        list.add(ques6)
        var ques7 = Question(7,"Which Indian Famous personality is this?",R.drawable.lm,"Asha Bhosnle","Lata Mangeshkar","Srinavasan","None of Above",2)
        list.add(ques7)
        var ques8 = Question(8,"Which Indian Famous personality is this?",R.drawable.st,"Michael Vaughan","Peter Fernandis","Sachin Tendulkar","None of Above",3)
        list.add(ques8)
        var ques9 = Question(9,"Which Indian Famous personality is this?",R.drawable.mt,"Mother Teresa","Srinavasan","Villiam Catherine","Anjezë Gonxhe",1)
        list.add(ques9)
        var ques10 = Question(10,"Which Indian Famous personality is this?",R.drawable.svp,"Rob Schneider","Brian Hallisay","Laxmanrao Kashinat","Sardar Vallabhai Patel",4)
        list.add(ques10)
        return list
    }
    fun getQuestionsQuiz3(): ArrayList<Question>{
        var list = ArrayList<Question>()
        var ques1 = Question(1,"Which Car brand is this?",R.drawable.honda,"Hyundai","Nexa","Honda","Mercedes",3)
        list.add(ques1)
        var ques2 = Question(2,"Which Car brand is this?",R.drawable.mahindra,"Mahindra","Suzuki","Orient","None",1)
        list.add(ques2)
        var ques3 = Question(3,"Which Car brand is this?",R.drawable.hyundai,"Hyundai","Porsche","Tesla","Honda",1)
        list.add(ques3)
        var ques4 = Question(4,"Which Car brand is this?",R.drawable.mazda,"Ford","Mahindra","Chevrolet","Mazda",4)
        list.add(ques4)
        var ques5 = Question(5,"Which Car brand is this?",R.drawable.mercedes,"Ferrari","Tesla","Mercedes","BMW",3)
        list.add(ques5)
        var ques6 = Question(6,"Which Car brand is this?",R.drawable.suzuki,"Hyundai","Suzuki","Nexa","Camaro",2)
        list.add(ques6)
        var ques7 = Question(7,"Which Car brand is this?",R.drawable.porsche,"Ferrari","Porsche","Cadillac","Ford",2)
        list.add(ques7)
        var ques8 = Question(8,"Which Car brand is this?",R.drawable.tesla,"Tesla","wolksvagon","Toyota","Tata",1)
        list.add(ques8)
        var ques9 = Question(9,"Which Car brand is this?",R.drawable.toyota,"Honda","Hyundai","Toyota","None",3)
        list.add(ques9)
        var ques10 = Question(10,"Which Car brand is this?",R.drawable.volkswagen,"Tata","Suzuki","Mahindra","Wolksvagon",4)
        list.add(ques10)
        return list
    }
    fun getQuestionsQuiz4(): ArrayList<Question>{
        var list = ArrayList<Question>()
        var ques1 = Question(1,"Which Computer Equipment is this?",R.drawable.monitor,"Display Vision","CPU","Monitor","Hard Disk",3)
        list.add(ques1)
        var ques2 = Question(2,"Which Computer Equipment is this?",R.drawable.mouse,"Mouse","Keyboard","FLoppy Disk","Pendrive",1)
        list.add(ques2)
        var ques3 = Question(3,"Which Computer Equipment is this?",R.drawable.keyboard,"Mouse","CD/DVD","Laptop","Keyboard",4)
        list.add(ques3)
        var ques4 = Question(4,"Which Computer Equipment is this?",R.drawable.cpu,"Processor","Motherboard","Webcam","CPU",4)
        list.add(ques4)
        var ques5 = Question(5,"Which Computer Equipment is this?",R.drawable.cs,"Disks","CD/DVD","Hard Disk","None of Above",2)
        list.add(ques5)
        var ques6 = Question(6,"Which Computer Equipment is this?",R.drawable.webcam,"Microphone","Webcam","Visualizer","Pen",2)
        list.add(ques6)
        var ques7 = Question(7,"Which Computer Equipment is this?",R.drawable.microphone,"Microphone","Joystick","Pen Handler","Printer",1)
        list.add(ques7)
        var ques8 = Question(8,"Which Computer Equipment is this?",R.drawable.floppydisk,"Floppy Disks","Hard Disks","Optical Disks","None of Above",1)
        list.add(ques8)
        var ques9 = Question(9,"Which Computer Equipment is this?",R.drawable.joystick,"Remote Play","Handler","Joystick","Webcam",3)
        list.add(ques9)
        var ques10 = Question(10,"Which Computer Equipment is this?",R.drawable.speaker,"CPU","Hazardas","Game Player","Speakers",4)
        list.add(ques10)
        return list
    }
    fun getQuestionsQuiz5(): ArrayList<Question>{
        var list = ArrayList<Question>()
        var ques1 = Question(1,"What is full form of ISRO?",R.drawable.isro,"Island special research options","Indian sovereignity and rev orders","Indian special Rectify Organization","Indian Space Research Organization",4)
        list.add(ques1)
        var ques2 = Question(2,"What is full form of CPU?",R.drawable.cpufull,"Control Processing Unit","Control Processed Unit","Central Processed Unified","Central Processing Unit",4)
        list.add(ques2)
        var ques3 = Question(3,"What is full form of ATM?",R.drawable.atm,"Automated Teller Machine","Automatic Transfer Machine","Automatic todo machine","None Of Above",1)
        list.add(ques3)
        var ques4 = Question(4,"What is full form of HTML?",R.drawable.html,"Hyper Too many language","Hypertext Markup Language","Hypertechnology Markup Language","None of Above",2)
        list.add(ques4)
        var ques5 = Question(5,"What is full form of WWW?",R.drawable.www,"Why where when","World Wide Web","What way would","World way web",2)
        list.add(ques5)
        var ques6 = Question(6,"What is full form of NGO?",R.drawable.ngo,"Non-governmental organization","Non grammatical order","No government order","None of Above",1)
        list.add(ques6)
        var ques7 = Question(7,"What is full form of IPL?",R.drawable.ipl,"Indian premier League","Indian parse lot","India's paramilitary league","None of Above",1)
        list.add(ques7)
        var ques8 = Question(8,"What is full form of WHO?",R.drawable.who,"Winning Health Officials","World Hurricane Organization","World Health Organization","World honey othernity",3)
        list.add(ques8)
        var ques9 = Question(9,"What is full form of BSF?",R.drawable.bsf,"Bhartiya Security Forces","Border safe firm","Border Security Forces","None of Above",3)
        list.add(ques9)
        var ques10 = Question(10,"What is full form of RBC?",R.drawable.rbc,"Royal bank california","Red Black Ceiling","Rayn Blood Circulation","Red Blood Cells",4)
        list.add(ques10)
        return list
    }
    fun getQuestionsQuiz6(): ArrayList<Question>{
        var list = ArrayList<Question>()
        var ques1 = Question(1,"What Indian city is the capital of two states?",R.drawable.city,"Mumbai","Kolkata","Chandigarh","Chennai",3)
        list.add(ques1)
        var ques2 = Question(2,"How many countries border India?",R.drawable.border,"14","6","2","9",2)
        list.add(ques2)
        var ques3 = Question(3,"What, approximately, is the area of India, in square kilometers?",R.drawable.area,"1500000","2000000","4000000","3000000",4)
        list.add(ques3)
        var ques4 = Question(4,"who is current president of india?",R.drawable.president,"Pranab Mukhrjee","Ram Nath Kovind","Narendra Modi","Narsimha Rao",2)
        list.add(ques4)
        var ques5 = Question(5,"Delhi is located along what river?",R.drawable.delhi,"The Ganga","The Yamuna","The Brahmputra","The Nile",2)
        list.add(ques5)
        var ques6 = Question(6,"When is India’s Independence Day?",R.drawable.aug,"July 26","August 15","October 31","January 1",2)
        list.add(ques6)
        var ques7 = Question(7,"Which of these is not a river of India?",R.drawable.rivers,"Ganges","Brahmaputra","Yamuna","Mekong",4)
        list.add(ques7)
        var ques8 = Question(8,"In what state is Bengaluru located?",R.drawable.bng,"Chhattisgarh","Bihar","Karnatka","Kerla",3)
        list.add(ques8)
        var ques9 = Question(9,"Which Indian president is nicknamed “Missile Man?”",R.drawable.apj,"Kocheril Raman Narayanan","Ram Nath Kovind","A.P.J. Abdul Kalam","Sarvepalli Radhakrishnan",3)
        list.add(ques9)
        var ques10 = Question(10,"What is the currency of India?",R.drawable.rupee,"Rupees","Yen","Dollar","Pounds",1)
        list.add(ques10)
        return list
    }
    fun getQuestionsQuiz7(): ArrayList<Question>{
        var list = ArrayList<Question>()
        var ques1 = Question(1,"Which Animal is shown in picture below?",R.drawable.lion,"Jaguar","Lion","Leopord","Tiger",2)
        list.add(ques1)
        var ques2 = Question(2,"Which Animal is shown in picture below?",R.drawable.monkey,"Monkey","Chimpanzee","Lemurus","Apes",1)
        list.add(ques2)
        var ques3 = Question(3,"Which Animal is shown in picture below?",R.drawable.elephant,"Elephant","Sea cow","Hyrax","Giraffe",1)
        list.add(ques3)
        var ques4 = Question(4,"Which Animal is shown in picture below?",R.drawable.tiger,"Leopord","Tiger","Jaguar","Snow Leopord",2)
        list.add(ques4)
        var ques5 = Question(5,"Which Animal is shown in picture below?",R.drawable.dog,"Gray Wolf","Dhole","Dog","Goat",3)
        list.add(ques5)
        var ques6 = Question(6,"Which Animal is shown in picture below?",R.drawable.rhino,"Horses","Tapris","Extravades","Rhino",4)
        list.add(ques6)
        var ques7 = Question(7,"Which Animal is shown in picture below?",R.drawable.cat,"Fossa","Genet","Mongoose","Cat",4)
        list.add(ques7)
        var ques8 = Question(8,"Which Animal is shown in picture below?",R.drawable.cow,"Cow","Calf","Bull","Cattle",1)
        list.add(ques8)
        var ques9 = Question(9,"Which Animal is shown in picture below?",R.drawable.zebra,"Giraffe","Zebra","Horse","None of Above",2)
        list.add(ques9)
        var ques10 = Question(10,"Which Animal is shown in picture below?",R.drawable.snake,"Crocodiles","Lizards","Snake","None of Above",3)
        list.add(ques10)
        return list
    }
    fun getQuestionsQuiz8(): ArrayList<Question>{
        var list = ArrayList<Question>()
        var ques1 = Question(1,"Which famous cricketer is this?",R.drawable.dhoni,"MS Dhoni","Virat Kohli","Jasprit Bumrah","Yuzvendra Chahal",1)
        list.add(ques1)
        var ques2 = Question(2,"Which famous cricketer is this?",R.drawable.wasim,"Younis Khan","Imran Khan","Shahid Afridi","Wasim Akram",4)
        list.add(ques2)
        var ques3 = Question(3,"Which famous cricketer is this?",R.drawable.gayle,"Marcon Marshal","Michael Holding","Chris Gayle","Brian Lara",3)
        list.add(ques3)
        var ques4 = Question(4,"Which famous cricketer is this?",R.drawable.virat,"Ravindra Jadeja","Hardik Pandya","Gautam Gambhir","Virat Kohli",4)
        list.add(ques4)
        var ques5 = Question(5,"Which famous cricketer is this?",R.drawable.ab,"Shoun Pollock","Ragiso Rabada","AB de Villiers","Imran Tahir",3)
        list.add(ques5)
        var ques6 = Question(6,"Which famous cricketer is this?",R.drawable.smith,"Adam Zampa","Steve Smith","Nathan Lyon","Marcus Stoinis",2)
        list.add(ques6)
        var ques7 = Question(7,"Which famous cricketer is this?",R.drawable.lee,"Mitchel Starc","Brat Lee","ALex Carry","Kane Richardson",2)
        list.add(ques7)
        var ques8 = Question(8,"Which famous cricketer is this?",R.drawable.ricky,"Ben Cutting","Ricky Ponting","Ben Stokes","Jackson Bird",2)
        list.add(ques8)
        var ques9 = Question(9,"Which famous cricketer is this?",R.drawable.lara,"Brian Lara","Clieve Llyod","Frank Worrel","Chris gayle",1)
        list.add(ques9)
        var ques10 = Question(10,"Which famous cricketer is this?",R.drawable.peterson,"Everton Weeks","Nathan Lyon","Michael Holding","Kevin Peterson",4)
        list.add(ques10)
        return list
    }
    fun getQuestionsQuiz9(): ArrayList<Question>{
        var list = ArrayList<Question>()
        var ques1 = Question(1,"Which Indian festival is associated with colors?",R.drawable.colors,"Holi","Diwali","Onam","Pongal",1)
        list.add(ques1)
        var ques2 = Question(2,"Which Indian cricketer became the first sportsman to be awarded the Bharat Ratna, India's highest civilian order?",R.drawable.st,"Sachin Tendulkar","Kapil Dev","MS Dhoni","Sunil Gavaskar",1)
        list.add(ques2)
        var ques3 = Question(3,"Which is the most populous state in India?",R.drawable.up,"Rajasthan","Maharashtra","Punjab","Uttar Pradesh",4)
        list.add(ques3)
        var ques4 = Question(4,"Who is the chairman of Reliance Industries limited?",R.drawable.ma,"Isha Ambani","Mukesh Ambani","Anil Ambani","Nita Ambani",2)
        list.add(ques4)
        var ques5 = Question(5,"Who is the only Indian cricketer to have scored 5000 runs in Test Cricket?",R.drawable.kd,"Virat Kohli","Kapil Dev","Sachin Tendulkar","MS Dhoni",2)
        list.add(ques5)
        var ques6 = Question(6,"In which year did the union government of India dissolve the government of Jammu and Kashmir?",R.drawable.jk,"1947","1980","2018","2002",3)
        list.add(ques6)
        var ques7 = Question(7,"Which Indian Satelite found water on the Moon?",R.drawable.satelite,"Chandrayaan-1","Mangalyaan","Cartosat-3","None has founded",1)
        list.add(ques7)
        var ques8 = Question(8,"Which is the national tree of India?",R.drawable.tree,"Mango Tree","Banyan Tree","Neem Tree","Peepal Tree",2)
        list.add(ques8)
        var ques9 = Question(9,"Which of these is a union territory of India?",R.drawable.jk,"Shimla","Ladakh","Kolkata","Bombay",2)
        list.add(ques9)
        var ques10 = Question(10,"Who wrote the Ramayana?",R.drawable.ramayna,"Tulsidasa Ji","Kalidas Ji","Ved Vyas Ji","Valmiki Ji",4)
        list.add(ques10)
        return list
    }
    fun getQuestionsQuiz10(): ArrayList<Question>{
        var list = ArrayList<Question>()
        var ques1 = Question(1,"Identify Application from it's Icon?",R.drawable.twitter,"Trello","Whatsapp","Instagram","Twitter",4)
        list.add(ques1)
        var ques2 = Question(2,"Identify Application from it's Icon?",R.drawable.sc,"Snapchat","Messenger","Facebook","Wickr",1)
        list.add(ques2)
        var ques3 = Question(3,"Identify Application from it's Icon?",R.drawable.insta,"Pinterest","Instagram","Tumbler","Flickr",2)
        list.add(ques3)
        var ques4 = Question(4,"Identify Application from it's Icon?",R.drawable.wsp,"Signal","Whatsapp","Telegram","Instagram",2)
        list.add(ques4)
        var ques5 = Question(5,"Identify Application from it's Icon?",R.drawable.fb,"Facebook","Instagram","Faceway","LinkedIn",1)
        list.add(ques5)
        var ques6 = Question(6,"Identify Application from it's Icon?",R.drawable.youtube,"DTube","MetaCafe","Youtube","Vevo",3)
        list.add(ques6)
        var ques7 = Question(7,"Identify Application from it's Icon?",R.drawable.gmail,"G-Mail","Yahoo","Outlook","Front",1)
        list.add(ques7)
        var ques8 = Question(8,"Identify Application from it's Icon?",R.drawable.uber,"Ola","Rapid","Uber","Swiggy",3)
        list.add(ques8)
        var ques9 = Question(9,"Identify Application from it's Icon?",R.drawable.amazon,"Flipkart","Amazon","Myantra","Ajio",2)
        list.add(ques9)
        var ques10 = Question(10,"Identify Application from it's Icon?",R.drawable.udemy,"CodeChef","Coursera","UdeChefTo","Udemy",4)
        list.add(ques10)
        return list
    }
}